### ISSUE TITLE
Warning: The dynamicInstantiate loader hook has been removed.

### ISSUE THREAD

**Issue by yoursunny** [K-FOSS/TS-ESNode#105]
`dynamicInstantiate` loader hook is gone since Node v14.5.0.
It causes warning:
```
Warning: The dynamicInstantiate loader hook has been removed.
```

For some code, including the test suite of this repository, it causes error:
```
RangeError [ERR_UNKNOWN_MODULE_FORMAT]: Unknown module format: dynamic
    at Loader.getModuleJob (internal/modules/esm/loader.js:236:13)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:53:21)
    at async Promise.all (index 3)
    at async link (internal/modules/esm/module_job.js:58:9) {
  code: 'ERR_UNKNOWN_MODULE_FORMAT'
}
```

https://github.com/nodejs/node/pull/33501 explains why they removed `dynamicInstantiate`.

**Comment by KristianFJones** [comment]
Well, fuck. Any ideas how we can work around this while still supporting drop in compatibility with older libraries?

**Comment by KristianFJones** [comment]
As happy as I am that I *have* to remove the hack, I don't know any other "easy" way of supporting external modules with fucky exports.

**Comment by KristianFJones** [comment]
I just got deep into a server administration project for work, I might not be able to get to solving this quickly, I've been burned out from programming for a little bit, although I'd be happy to review, test, and merge a potential solution if anyone wants.

**Comment by KristianFJones** [comment]
So, after taking a 3 month break from programming. I'm back, I almost have a fix for this. I can't get React SSR tests working, otherwise everything else is functional

**Comment by KristianFJones** [comment]
Fix has been released. I haven't tested it in my projects yet. But all tests are passing.

**Comment by yoursunny** [comment]
It's working for me on Node 14.11.
https://github.com/yoursunny/NDNts/commit/65e493a7bb9ba9f72cfd5640bc2ecc33a8621d5d

**Comment by KristianFJones** [comment]
> It's working for me on Node 14.11.
> [yoursunny/NDNts@65e493a](https://github.com/yoursunny/NDNts/commit/65e493a7bb9ba9f72cfd5640bc2ecc33a8621d5d)

Awesome, sorry for the delay on fixing this one. Took a bit of a break from programming.

**Comment by KristianFJones** [comment]
I also have it working in my new [SSH-Proxy](https://github.com/KristianFJones/SSH-Proxy) which is using the latest `node:alpine3.12` image in the dev container. I haven't fully tested if `@k-foss/ts-esnode=>1.7.0` works with node 14.4 and below, but the tests appear to be passing in Node.JS 13.8
