### ISSUE TITLE
Import of modules not  working on windows: Path not formatted correctly

### ISSUE THREAD

**Issue by zotta** [K-FOSS/TS-ESNode#39]
I noticed the function dynamicInstantiate(url) splits the path and creates a require function. The problem on windows is that the URL starts with 'file:///c:/...' your function converts this into '/c:/...'.
It works if the path starts with 'c:/...' (no slash in front).

Could you please fix this? I think the correction should only be done if process.platform === 'win32'.

**Comment by KristianFJones** [comment]
I think that there is a FS or path function that I can use to transform/fix the path, I just don't use windows often, do you have any prior experience with supporting Windows and other file paths in NodeJS? I could really use some help on that department.

**Comment by yoursunny** [comment]
I'm facing the same issue. Either I messed up something in #45, or it's caused by one of the reverts prior to v1.4.0 release.
