### ISSUE TITLE
Error ERR_LOADER_CHAIN_INCOMPLETE: short circuit detection

### ISSUE THREAD

**Issue by leumasme** [K-FOSS/TS-ESNode#443]
When trying to launch a script with ts-esnode (both latest and 1.7.0) on Node v16.17.0, I am getting the error
```Error [ERR_LOADER_CHAIN_INCOMPLETE]: "@k-foss/ts-esnode 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return```
I could find [ts-node/issues/1714](https://github.com/TypeStrong/ts-node/issues/1714) (April 2022) for this error, which seems to imply that this error comes from new checks in new Node version.
It would be great if you could look into this and update the package to resolve this.
Thanks

**Comment by KristineFJ** [comment]
Hey... Sorry I've been burned out for awhile. Fixing this now
